106 to reate table
it-volunteers-ukraine/ChariERP pull request #109
Opened 2024-07-21 13:06 UTC by Kyslytsia

2024-07-22 10:49 UTC, ASGladchenko approved these changes

2024-07-23 19:20 UTC, Wolshebnik requested changes

2024-07-23 19:20 UTC, Wolshebnik commented on client/tailwind.config.ts
> +    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
'./src/pages/**/*.{js,ts,jsx,tsx,mdx}'
 remove pls
it not need anymore

2024-07-23 19:20 UTC, Wolshebnik commented on client/src/components/pages/table-requests/mock.ts
> +export default data;
why default export?

2024-07-23 19:20 UTC, Wolshebnik commented on client/src/components/pages/table-requests/index.tsx
> +export default TableRequests;
Why default export

2024-07-23 19:20 UTC, Wolshebnik commented on client/src/components/pages/table-organization/row-item.tsx
> +export default RowItem;
Why default export

2024-07-23 19:20 UTC, Wolshebnik commented on client/src/components/pages/table-organization/mock.ts
> +export default data;
why default export?

2024-07-23 19:20 UTC, Wolshebnik commented on client/src/components/pages/table-organization/index.tsx
> +export default TableOrganization;
Why default export?

2024-07-23 19:20 UTC, Wolshebnik commented on client/src/app/[locale]/(admin)/admin/requests/page.tsx
> +import TableRequests from '@/components/pages/table-requests';
use import from just @/components

2024-07-23 19:20 UTC, Wolshebnik commented on client/src/app/[locale]/(admin)/admin/organizations/page.tsx
> +import TableOrganization from '@/components/pages/table-organization';
use import from just @/components

2024-07-23 19:20 UTC, Wolshebnik commented on client/src/app/[locale]/(admin)/admin/declined/page.tsx
> +import TableRequests from '@/components/pages/table-requests';
use import from just @/components
and sort

2024-07-24 16:41 UTC, merged