253 create a taskcard for the board page with tasks
it-volunteers-ukraine/ChariERP pull request #260
Opened 2024-10-11 12:30 UTC by VladDot

Create a taskcard for the board page 
Implemented functional deletion for the task card
Added icon DotSettings
Created a temporary mock for the example

2024-10-11 14:14 UTC, Kyslytsia approved these changes

2024-10-11 14:14 UTC, Kyslytsia commented on client/src/components/board-task-card/card/index.tsx
> +  const { deleteWindow } = getStyle({ isActive });
All constants must be at the top
State below

2024-10-12 07:04 UTC, ASGladchenko approved these changes

2024-10-12 10:14 UTC, Wolshebnik requested changes

2024-10-12 10:14 UTC, Wolshebnik commented on client/src/components/board-task-card/card/index.tsx
> +  data: IMockCards[];
wrong name

2024-10-18 08:26 UTC, Wolshebnik commented on client/src/app/[locale]/(provider)/manager/dashboards/board/[slug]/page.tsx
> +'use client';
space

2024-10-18 08:26 UTC, Wolshebnik commented on client/src/app/[locale]/(provider)/manager/dashboards/board/[slug]/page.tsx
>  import { BoardTitle } from './board-title';
space

2024-10-18 08:26 UTC, Wolshebnik commented on client/src/app/[locale]/(provider)/manager/dashboards/board/[slug]/page.tsx
> +      <TaskCard
remove

2024-10-18 08:26 UTC, Wolshebnik commented on client/src/components/tools-drop-menu/style.ts
> +// import clsx from 'clsx';
remove

2024-10-18 08:26 UTC, Wolshebnik commented on client/src/components/tools-drop-menu/style.ts
> +    // },
remove

2024-10-18 09:29 UTC, Wolshebnik approved these changes

2024-10-18 09:36 UTC, merged