30 phone format input field
it-volunteers-ukraine/ChariERP pull request #45
Opened 2024-05-14 18:10 UTC by MarinaMostova

2024-05-14 18:50 UTC, Wolshebnik requested changes

2024-05-14 18:50 UTC, Wolshebnik commented on client/src/components/input/styles.ts
> +  cross,
sort

2024-05-14 18:50 UTC, Wolshebnik commented on client/src/components/input/index.tsx
> +  cross = false,
false param not need

2024-05-14 18:53 UTC, Wolshebnik commented on client/src/components/input/index.tsx
> +  isMasked = false,
the same

2024-05-21 06:29 UTC, Wolshebnik approved these changes

2024-05-21 17:15 UTC, rpkyrych approved these changes

2024-05-21 17:15 UTC, merged