finish
it-volunteers-ukraine/ChariERP pull request #50
Opened 2024-05-26 10:42 UTC by ASGladchenko

2024-05-26 16:12 UTC, Wolshebnik requested changes

2024-05-26 16:12 UTC, Wolshebnik commented on client/src/components/date-field/index.tsx
> +                  error={(meta.error && meta.error) || ''}
fix pls

2024-05-26 16:12 UTC, Wolshebnik commented on client/src/components/date-field/style.css
> +  @apply content-['ASD'] absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-full;
what is it? content-[ASD]

2024-05-28 09:56 UTC, Wolshebnik approved these changes

2024-05-28 14:15 UTC, Kyslytsia approved these changes

2024-05-28 17:02 UTC, merged