70 to collect all inputs
it-volunteers-ukraine/ChariERP pull request #91
Opened 2024-06-24 14:56 UTC by Kyslytsia

2024-06-24 15:47 UTC, Wolshebnik requested changes

2024-06-24 15:47 UTC, Wolshebnik commented on client/src/components/checkbox-radio/index.tsx
> +          ref={itemRef}
sort

2024-06-24 16:18 UTC, rpkyrych commented on client/src/app/[locale]/(admin)/dashboard/config.ts
> +}
It'd be better to use OOP paradigm here: spit the object into a few other (Organization, Representative) and to use aggregation for those objects.

2024-06-24 16:18 UTC, rpkyrych commented on client/src/app/[locale]/(admin)/dashboard/config.ts
> +export const validationSchema = (
The name of the constant doesn't provide an information to whom those validation belong. It'd be more beneficial to rename it.

2024-06-24 16:18 UTC, rpkyrych commented on client/src/app/[locale]/(admin)/dashboard/page.tsx
> +    console.log('data', values);
The log message should better describe logged value

2024-06-24 16:18 UTC, rpkyrych commented on client/src/components/checkbox-radio-field/index.tsx
> +            const value = type === 'radio' ? e.target.value : e.target.checked;
The name of the variable doesn't explain what is the content or purpose of the value in it.

2024-06-28 17:39 UTC, Wolshebnik requested changes

2024-06-28 17:39 UTC, Wolshebnik commented on client/src/app/[locale]/(admin)/dashboard/[id]/page.tsx
> +const Dashboard1 = () => {
so-so Name

2024-06-28 17:39 UTC, Wolshebnik commented on client/src/app/[locale]/(admin)/dashboard/[id]/page.tsx
> +  const router = useRouter();
should be moved to the top of the list

2024-06-28 17:39 UTC, Wolshebnik commented on client/src/app/[locale]/(login)/sign-up/sign-up.tsx
> +  organizationValidation,
sort

2024-06-29 15:39 UTC, Wolshebnik approved these changes

2024-06-29 16:56 UTC, rpkyrych approved these changes

2024-06-29 17:11 UTC, merged